# Generated by Django 4.2.29 on 2026-03-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="notes_files/"),
        ),
    ]
